#! /bin/bash

# Note this script only works if you have brew installed postgres on a mac.
# If you have not, or do not have a mac, you will need to install postgres, and ensure
# it added these following CLI tools: psql, dropdb, createdb, and pg_dump CLI tools (https://stackoverflow.com/questions/7975556/how-to-start-postgresql-server-on-mac-os-x)
# See for info on commands https://www.brianstorti.com/understanding-shell-script-idiom-redirect/
# See https://askubuntu.com/questions/12098/what-does-outputting-to-dev-null-accomplish-in-bash-scripts
command -v psql >/dev/null 2>&1 || { echo >&2 "Aborting: psql CLI not installed, please install postgres with your OS"; exit 1; }
command -v dropdb >/dev/null 2>&1 || { echo >&2 "Aborting: dropdb CLI not installed, please install postgres with your OS"; exit 1; }
command -v createdb >/dev/null 2>&1 || { echo >&2 "Aborting: createdb CLI not installed, please install postgres with your OS"; exit 1; }
command -v pg_dump >/dev/null 2>&1 || { echo >&2 "Aborting: pg_dump CLI not installed, please install postgres with your OS"; exit 1; }


# Env for local postgres server
PG_LOCAL_DB_NAME="${PG_LOCAL_DB_NAME:-saga}"
PG_LOCAL_OWNER="${PG_LOCAL_OWNER:-postgres}"
PG_LOCAL_HOST="${PG_LOCAL_HOST:-localhost}"

# Env for remote server on gcloud
PG_REMOTE_DB_NAME="${PG_REMOTE_DB_NAME:-saga-data-dev}"
PG_REMOTE_USER="${PG_REMOTE_OWNER:-saga}"
PG_REMOTE_HOST="${PG_REMOTE_HOST:-aa13ivyx4283ufi.cjukwq7hl0d6.us-east-1.rds.amazonaws.com}"

# Shared env for local and remote server
PG_PORT="${PG_PORT:-5432}"

# Drop db if it exists, see: https://stackoverflow.com/questions/14549270/check-if-database-exists-in-postgresql-using-shell
if psql -lqt | cut -d \| -f 1 | grep -qw $PG_LOCAL_DB_NAME; then
    # database exists
    dropdb $PG_LOCAL_DB_NAME
    # Attempt to catch error: see: https://stackoverflow.com/questions/16931244/checking-if-output-of-a-command-contains-a-certain-string-in-a-shell-script
    # if dropdb $PG_LOCAL_DB_NAME | grep -q "createdb"; then
    #   echo "Cannot drop db, please close all connections"
    # fi
    # $? is 0
fi

# Create db
createdb $PG_LOCAL_DB_NAME \
  --echo \
  --owner=$PG_LOCAL_OWNER \
  --host=$PG_LOCAL_HOST \
  --port=$PG_PORT

echo "Please enter password for remote postgres server"
pg_dump $PG_REMOTE_DB_NAME > db/dump -h $PG_REMOTE_HOST -p $PG_PORT -U $PG_REMOTE_USER

echo "Inserting dump into local, please enter password for local postgres server"
psql -h localhost -p 5432 $PG_LOCAL_DB_NAME < ./db/dump


exit;